name: Deploy on Open Pull Request

on:
  pull_request:
    types:
      - opened

jobs:
  deploy:
    runs-on: ubuntu-latest # runner for the pull request trigger 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # equivalent to git clone inside the runner 

      - name: Set up Python
        uses: actions/setup-python@v2 # use action from git hub 
        with:
          python-version: 3.9.17 # Replace with your desired Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Deploy Your Application
        run: |
          # Add your deployment commands here
          # For example, you might use a script to deploy your Flask app
          python3 ./deploy_test.py
